#!/usr/bin/env python3

import os
import robot_upstart

from ament_index_python.packages import get_package_share_directory


def get_package_file(package, file_path):
    """Get the location of a file installed in an ament package"""
    package_path = get_package_share_directory(package)
    absolute_file_path = os.path.join(package_path, file_path)
    return absolute_file_path


main_job = robot_upstart.Job(workspace_setup=os.environ['ROBOT_SETUP'])
main_job.symlink = True
main_job.add(package="ridgeback_base", filename="launch/base.launch")
# main_job.add(package="ridgeback_bringup", filename="launch/accessories.launch")
main_job.install()

# Wait to for can-udp-bridge to be up before starting ROS
os.system("sudo sed -i '/After/c After=can-udp-bridge.service' /lib/systemd/system/ros.service")


class RidgebackExtras(robot_upstart.providers.Generic):
    def post_install(self):
        pass

    def generate_install(self):
        with open(get_package_file('ridgeback_bringup', 'can-udp-bridge.conf')[0]) as f:
            can_conf_contents = f.read()
        with open(get_package_file('ridgeback_bringup', 'can-udp-bridge.sh')[0]) as f:
            can_sh_contents = f.read()
        return {
            "/lib/systemd/system/can-udp-bridge.service": {
                "content": can_conf_contents,
                "mode": 0o644
            },
            "/usr/sbin/can-udp-bridge": {
                "content": can_sh_contents,
                "mode": 0o755
            },
            "/etc/systemd/system/multi-user.target.wants/can-udp-bridge.service": {
                "symlink": "/lib/systemd/system/can-udp-bridge.service"
            }}


other_job = robot_upstart.Job()
other_job.install(Provider=RidgebackExtras)
